version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      frontend:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker:
        patterns:
          - "*"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
    groups:
      backend:
        patterns:
          - "*"
