coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
fixes:
  - "/src::/src/backend"
codecov:
  disable_default_path_fixes: true
