services:
  backend-tests:
    build:
      dockerfile: tests.Dockerfile
      context: src/backend
    container_name: deevenue-backend-tests
    restart: no
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    volumes:
      - ./coverage:/results
      # Required for testcontainers
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
