name: Test slow deployments

on:
  push:
    branches-ignore: ["main"]
  workflow_dispatch:

jobs:
  ping-deployment-for-testing:
    name: "Ping deployment for testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mask secret
        run: |
          FFF=$(echo "${{ secrets.DEPLOYMENT_API_URL }}" | sed -e "s|https://|$1|g" -e "s|/||g")
          echo "::add-mask::$FFF"
      - name: Print debug info
        run: |
          curl --version
      - name: Ping deployment verbosely
        run: |
          curl -vvv ${{ secrets.DEPLOYMENT_API_URL }}
