name: Test slow deployments

on:
  push:
    branches-ignore: ["main"]
  workflow_dispatch:

jobs:
  ping-deployment-for-testing:
    name: "Ping deployment for testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print debug info
        run: |
          curl --version
      - name: Ping deployment using GET with correct auth
        run: |
          curl -H "Authorization: Bearer ${{ secrets.DEPLOYMENT_TOKEN }}" ${{ secrets.DEPLOYMENT_API_URL }}
