name: Run tests

on:
  - push
  - workflow_dispatch

jobs:
  Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build test projects
        uses: docker/build-push-action@v6
        with:
          push: false
          context: "{{defaultContext}}:src/backend"
          file: tests.Dockerfile
      - uses: actions/checkout@v4
      - name: Run tests
        run: bash scripts/tests-backend.sh
      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/*
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./coverage/report
          files: ./coverage/report/lcov.info,./coverage/report/Cobertura.xml
